### ISSUE TITLE
Error: the `uses' attribute must be a path, a Docker image, or owner/repo@ref

### ISSUE THREAD

**Issue by george-gca** [dsanders11/json-schema-validate-action#30]
The action is currently throwing:

```
Error
the `uses' attribute must be a path, a Docker image, or owner/repo@ref
```

As can be seen on [this failed workflow](https://github.com/alshedivat/al-folio/actions/runs/12992950152).

**Comment by techman83** [comment]
Example is incorrect, should be

```yaml
      - name: Validate workflows
        if: steps.check-for-changed-workflows.outputs.any_changed == 'true'
        uses: dsanders11/json-schema-validate-action@v1.2.0
        with:
          schema: https://json.schemastore.org/github-workflow.json
          files: .github/workflows/**.yml
```

It would be useful to have a reference `@v1`, it looks as though most projects just update the tag on release or via a workflow

https://github.com/actions/checkout/blob/main/.github/workflows/update-main-version.yml
